---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tenant1
  namespace: flux-system
spec:
  interval: 60m
  wait: false
  timeout: 3m
  retryInterval: 1m
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./tenants/tenant1/workloads/flux-kustomization
