---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v2.8.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: kubernetes-sigs/kind@v0.12.0
- name: fluxcd/flux2@v0.29.3
