---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
registries:
- type: standard
  ref: v3.106.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: kubernetes-sigs/kind@v0.17.0
- name: fluxcd/flux2@v0.38.0
- name: kubernetes-sigs/kustomize@kustomize/v4.5.7
