apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomization
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kustomization
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
