---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-kustomization
  namespace: flux-system
spec:
  interval: 60m
  wait: true
  timeout: 1m
  retryInterval: 1m
  prune: true
  force: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  path: ./tenants/tenant1/workloads/flux-kustomization
  targetNamespace: flux-kustomization
